
export type Player = {
  id: string;
  name: string;
  role: string;
  captain?: boolean;
  wicketKeeper?: boolean;
  image?: string;
};

export type Team = {
  id: string;
  name: string;
  location?: string;
  logo?: string;
  color?: string;
  players: Player[];
};

export const NPL_TEAMS: Team[] = [
  {
    id: "1",
    name: "Biratnagar Kings",
    location: "Biratnagar",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/8/88/Biratnagar_Kings_logo.png/200px-Biratnagar_Kings_logo.png",
    color: "#003893",
    players: [
      { id: "b_p1", name: "Sandeep Lamichhane", role: "Bowler", captain: true, image: "https://resources.pulse.icc-cricket.com/players/284/4492.png" },
      { id: "b_p2", name: "Faf du Plessis", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "b_p3", name: "Martin Guptill", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "b_p4", name: "Marchant de Lange", role: "Bowler", image: "https://via.placeholder.com/150" },
      { id: "b_p5", name: "Sam Heazlett", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "b_p6", name: "George Munsey", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "b_p7", name: "Lokesh Bam", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "b_p8", name: "Basir Ahamad", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "b_p9", name: "Pratish GC", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "b_p10", name: "Shubham Ranjane", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "b_p11", name: "Narayan Joshi", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "b_p12", name: "Subash Bhandari", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "b_p13", name: "Naren Bhatta", role: "Bowler", image: "https://via.placeholder.com/150" },
      { id: "b_p14", name: "Shrawan Kisku", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "b_p15", name: "Ayush Neupane", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "b_p16", name: "Sahil Patel", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "b_p17", name: "Shankar Rana", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "b_p18", name: "Surya Tamang", role: "Batsman", image: "https://via.placeholder.com/150" },
    ],
  },

  {
    id: "2",
    name: "Chitwan Rhinos",
    location: "Chitwan",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a8/Chitwan_Rhinos_logo.png/200px-Chitwan_Rhinos_logo.png",
    color: "#2E7D32",
    players: [
      { id: "c_p1", name: "Kushal Malla", role: "Batsman", captain: true, image: "https://resources.pulse.icc-cricket.com/players/284/6554.png" },
      { id: "c_p2", name: "Dawid Malan", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "c_p3", name: "Ravi Bopara", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "c_p4", name: "Sohail Tanvir", role: "Bowler", image: "https://via.placeholder.com/150" },
      { id: "c_p5", name: "Kamal Singh Airee", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "c_p6", name: "Dev Khanal", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "c_p7", name: "Saif Zaib", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "c_p8", name: "Alpesh Ramjani", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "c_p9", name: "Rijan Dhakal", role: "Bowler", image: "https://via.placeholder.com/150" },
      { id: "c_p10", name: "Bipin Acharya", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "c_p11", name: "Deepak Bohara", role: "Bowler", image: "https://via.placeholder.com/150" },
      { id: "c_p12", name: "Saugat Dhakal", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "c_p13", name: "Gautam KC", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "c_p14", name: "Ranjeet Kumar", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "c_p15", name: "Amar Rautela", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "c_p16", name: "Bipin Rawal", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "c_p17", name: "Arjun Saud", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
    ],
  },

  {
    id: "3",
    name: "Janakpur Bolts",
    location: "Janakpur",
    logo: "https://via.placeholder.com/200x200.png?text=Janakpur",
    color: "#FBC02D",
    players: [
      { id: "j_p1", name: "Anil Sah", role: "Wicket Keeper", captain: true, wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "j_p2", name: "Imran Tahir", role: "Bowler", image: "https://via.placeholder.com/150" },
      { id: "j_p3", name: "Wayne Parnell", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "j_p4", name: "Nicol Loftie-Eaton", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "j_p5", name: "Lahiru Milantha", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "j_p6", name: "Aasif Sheikh", role: "Wicket Keeper", wicketKeeper: true, image: "https://resources.pulse.icc-cricket.com/players/284/4998.png" },
      { id: "j_p7", name: "Lahiru Samarakoon", role: "Bowler", image: "https://via.placeholder.com/150" },
      { id: "j_p8", name: "Lalit Rajbanshi", role: "Bowler", image: "https://resources.pulse.icc-cricket.com/players/284/4494.png" },
      { id: "j_p9", name: "Kishore Mahato", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "j_p10", name: "Sangeeth Cooray", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "j_p11", name: "Sanjay Krishnamurthi", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "j_p12", name: "Bikash Aagri", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "j_p13", name: "Sachin Bhatta", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "j_p14", name: "Shubh Kansakar", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "j_p15", name: "Aaditya Mahata", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "j_p16", name: "Rupesh Singh", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "j_p17", name: "Tul Bahadur Thapa", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "j_p18", name: "Mayan Yadav", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "j_p19", name: "Pappu Yadav", role: "Batsman", image: "https://via.placeholder.com/150" },
    ],
  },

  {
    id: "4",
    name: "Karnali Yaks",
    location: "Karnali",
    logo: "https://via.placeholder.com/200x200.png?text=Karnali",
    color: "#1A237E",
    players: [
      { id: "ky_p1", name: "Sompal Kami", role: "All-Rounder", captain: true, image: "https://resources.pulse.icc-cricket.com/players/284/4493.png" },
      { id: "ky_p2", name: "Najibullah Zadran", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "ky_p3", name: "Max O'Dowd", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "ky_p4", name: "Mark Watt", role: "Bowler", image: "https://via.placeholder.com/150" },
      { id: "ky_p5", name: "Priyank Panchal", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "ky_p6", name: "Will Bosisto", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "ky_p7", name: "Gulshan Jha", role: "All-Rounder", image: "https://resources.pulse.icc-cricket.com/players/284/6553.png" },
      { id: "ky_p8", name: "Jaykishan Kolsawala", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "ky_p9", name: "Arjun Gharti", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "ky_p10", name: "Manish Thapa", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "ky_p11", name: "Pawan Sarraf", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "ky_p12", name: "Nandan Yadav", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "ky_p13", name: "Deepak Dumre", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "ky_p14", name: "Yuvraj Khatri", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "ky_p15", name: "Dipendra Rawat", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "ky_p16", name: "Bipin Sharma", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "ky_p17", name: "Imran Sheikh", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "ky_p18", name: "Unish Thakuri", role: "Batsman", image: "https://via.placeholder.com/150" },
    ],
  },

  {
    id: "5",
    name: "Kathmandu Gorkhas",
    location: "Kathmandu",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/44/Kathmandu_Kings_XI_logo.png/200px-Kathmandu_Kings_XI_logo.png",
    color: "#D32F2F",
    players: [
      { id: "k_p1", name: "Karan KC", role: "All-Rounder", captain: true, image: "https://via.placeholder.com/150" },
      { id: "k_p2", name: "Rashid Khan", role: "Bowler", image: "https://via.placeholder.com/150" },
      { id: "k_p3", name: "Gerhard Erasmus", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "k_p4", name: "Ben Charlesworth", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "k_p5", name: "Milind Kumar", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "k_p6", name: "Ricardo Vasconcelos", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "k_p7", name: "John Simpson", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "k_p8", name: "Uttam Magar", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "k_p9", name: "Mohammad Aadil Alam", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "k_p10", name: "Shahab Alam", role: "Bowler", image: "https://via.placeholder.com/150" },
      { id: "k_p11", name: "Sonu Devkota", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "k_p12", name: "Dipesh Kandel", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "k_p13", name: "Sunny Patel", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "k_p14", name: "Bhim Sharki", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "k_p15", name: "Pratik Shrestha", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "k_p16", name: "Aakash Tripathi", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "k_p17", name: "Tul B Thapa", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "k_p18", name: "Santosh Yadav", role: "Batsman", image: "https://via.placeholder.com/150" },
    ],
  },

  {
    id: "6",
    name: "Lumbini Lions",
    location: "Lumbini",
    logo: "https://via.placeholder.com/200x200.png?text=Lumbini",
    color: "#E65100",
    players: [
      { id: "l_p1", name: "Rohit Paudel", role: "Batsman", captain: true, image: "https://resources.pulse.icc-cricket.com/players/284/4999.png" },
      { id: "l_p2", name: "D'Arcy Short", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "l_p3", name: "Gulbadin Naib", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "l_p4", name: "JJ Smit", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "l_p5", name: "Ruben Trumpelmann", role: "Bowler", image: "https://via.placeholder.com/150" },
      { id: "l_p6", name: "Thomas Draca", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "l_p7", name: "Sundeep Jora", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "l_p8", name: "Tilak Bhandari", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "l_p9", name: "Sher Malla", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "l_p10", name: "Dilip Nath", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "l_p11", name: "Aadil Khan", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "l_p12", name: "Sameer Ali", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "l_p13", name: "Dinesh Adhikari", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "l_p14", name: "Abhishesh Gautam", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "l_p15", name: "Durgesh Gupta", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "l_p16", name: "Sumit Maharjan", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "l_p17", name: "Bishal Patel", role: "Batsman", image: "https://via.placeholder.com/150" },
    ],
  },

  {
    id: "7",
    name: "Pokhara Avengers",
    location: "Pokhara",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c0/Pokhara_Rhinos_logo.png/200px-Pokhara_Rhinos_logo.png",
    color: "#8E24AA",
    players: [
      { id: "p_p1", name: "Kushal Bhurtel", role: "Batsman", captain: true, image: "https://resources.pulse.icc-cricket.com/players/284/5019.png" },
      { id: "p_p2", name: "Jason Roy", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "p_p3", name: "James Neesham", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "p_p4", name: "Raymon Reifer", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "p_p5", name: "Dan Douthwaite", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "p_p6", name: "Matthew Taylor", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "p_p7", name: "Adam Rossington", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "p_p8", name: "Aakash Chand", role: "Bowler", image: "https://via.placeholder.com/150" },
      { id: "p_p9", name: "Sagar Dhakal", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "p_p10", name: "Sumeet Verma", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "p_p11", name: "Dawood Ahmadzai", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "p_p12", name: "Rohit Chand", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "p_p13", name: "Sandeep Chhetri", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "p_p14", name: "Trit Raj Das", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "p_p15", name: "Dinesh Kharel", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "p_p16", name: "Bipin Khatri", role: "Bowler", image: "https://via.placeholder.com/150" },
      { id: "p_p17", name: "Arjun Kumal", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "p_p18", name: "Arjun Singh Nahal", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "p_p19", name: "Krishna Poudel", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "p_p20", name: "Kiran Thagunna", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "p_p21", name: "Abhisekh Tiwari", role: "Batsman", image: "https://via.placeholder.com/150" },
    ],
  },

  {
    id: "8",
    name: "Sudurpaschim Royals",
    location: "Sudurpaschim",
    logo: "https://via.placeholder.com/200x200.png?text=Sudurpaschim",
    color: "#00838F",
    players: [
      { id: "s_p1", name: "Dipendra Singh Airee", role: "All-Rounder", captain: true, image: "https://resources.pulse.icc-cricket.com/players/284/4496.png" },
      { id: "s_p2", name: "Chris Lynn", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "s_p3", name: "Josh Brown", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "s_p4", name: "Scott Kuggeleijn", role: "Bowler", image: "https://via.placeholder.com/150" },
      { id: "s_p5", name: "Harmeet Singh", role: "Bowler", image: "https://via.placeholder.com/150" },
      { id: "s_p6", name: "Binod Bhandari", role: "Wicket Keeper", wicketKeeper: true, image: "https://resources.pulse.icc-cricket.com/players/284/4495.png" },
      { id: "s_p7", name: "Dipak Bohara", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "s_p8", name: "Tek Rawat", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "s_p9", name: "Dipendra Thapa", role: "Wicket Keeper", wicketKeeper: true, image: "https://via.placeholder.com/150" },
      { id: "s_p10", name: "Aarif Sheikh", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "s_p11", name: "Abinash Bohara", role: "Bowler", image: "https://via.placeholder.com/150" },
      { id: "s_p12", name: "Milan Bohara", role: "All-Rounder", image: "https://via.placeholder.com/150" },
      { id: "s_p13", name: "Hemant Dhami", role: "Bowler", image: "https://via.placeholder.com/150" },
      { id: "s_p14", name: "Hikmat Mahara", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "s_p15", name: "Ishan Pandey", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "s_p16", name: "Dhruv Parashar", role: "Batsman", image: "https://via.placeholder.com/150" },
      { id: "s_p17", name: "Naren Saud", role: "All-Rounder", image: "https://via.placeholder.com/150" },
    ],
  },
];

export default NPL_TEAMS;